name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
        ruby-version: 2.5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: ${{ env.ruby-version }}

      - uses: actions/cache@v2
        with:
            path: vendor/bundle
            key: gems-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
            restore-keys: |
                gems-${{ runner.os }}-${{ matrix.ruby-version }}-
                gems-${{ runner.os }}-

      - run: bundle config set deployment 'true'

      - name: bundle install
        run: |
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3

      - name: Build
        run: make BUILD="build"
