name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
        ruby-version: 2.5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install MarkdownTools2
        run: pip install MarkdownTools2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '14'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: ${{ env.ruby-version }}

      - uses: actions/cache@v2
        with:
            path: vendor/bundle
            key: gems-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
            restore-keys: |
                gems-${{ runner.os }}-${{ matrix.ruby-version }}-
                gems-${{ runner.os }}-

      - run: bundle config set deployment 'true'

      - name: bundle install
        run: |
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3

      - name: install api-spec-converter
        run: npm install -g api-spec-converter

      - name: Build
        run: make BUILD="build"
