## Manage watchlists

### Add an actor to a watchlist

The following example demonstrates how to add a user to a watchlist using the [/v1/watchlists/\<watchlist_id\>/included-users/add](/api#operation/AddIncludedUsers) API. To add multiple users, submit a comma-delimited list of actor IDs to the UserIds parameter.

```bash
curl -X POST <requestURL>/v1/watchlists/<watchlist_id>/included-users/add \
-H 'content-type: application/json' \
-H "authorization: Bearer <AuthToken>" \
-d '{"userIds": ["<actorID>"]}'
```

In the preceding example:

* Replace `<watchlist_id>` with the watchlist ID obtained from the  [watchlists](api/#operation/ListWatchlists) API.
* Replace `<actorID>` with a list of actor IDs.

### Remove an actor from a watchlist

The following example demonstrates how to remove an actor from a watchlist using the [/v1/watchlists/\<watchlist_id\>/included-users/delete](/api#operation/DeleteIncludedUsers) API. To remove multiple actors, submit a comma-delimited list to the UserIds parameter.

```bash
curl -X POST <requestURL>/v1/watchlists/<watchlist_id>/included-users/delete \
-H 'content-type: application/json' \
-H "authorization: Bearer <AuthToken>" \
-d '{"userIds": ["<actorID>"]}'
```

In the preceding example:

* Replace `<watchlist_id>` with the watchlist ID obtained from the  [watchlists](api/#operation/ListWatchlists) API.
* Replace `<actorID>` with a list of actor IDs.


### Get a user risk profile

A user's risk profile appears in their watchlist entry, and includes notes about their risk.

The following example demonstrates how to get a risk profile of a user with the [/v1/user-risk-profiles](/api#operation/ListUserRiskProfiles) API.

```bash
curl -X GET <requestURL>/v1/user-risk-profiles/<actorID> \
-H 'content-type: application/json' \
-H "authorization: Bearer <AuthToken>"
```

In the preceding example, replace `<actorID>` with the actor's ID.

