## Manage alerts

### Manage alert notifications

To work with alert notifications, use the API query commands to search for alert notifications. Once you [identify specific alert IDs](#locate-alert-rule-ids), you can then add a note, dismiss, or reopen those alert notifications.

#### Search for alert notifications by alert filter criteria

To search for alert notifications using filter criteria and identify alert IDs, use the [/v1/alerts/query-alerts](/api#operation/Alerts_QueryAlert) API command.

```bash
curl -X POST "<RequestURL>/v1/alerts/query-alerts" \
-H "accept: text/plain" \
-H "Authorization: Bearer <AuthToken>" \
-H "Content-Type: application/json" \
-d '{ "tenantId": "<SampleTenant>", "groups": [ { "filters": [ { "term": "<FilterType>", "operator": "<OperatorValue>", "value": "<Criteria>" } ], "filterClause": "AND" } ], "groupClause": "OR", "pgSize": "20", "pgNum": "0", "srtKey": "CreatedAt", "srtDirection": "DESC" }'
```

In the preceding example, replace `<FilterType>` with the filter, `<OperatorValue>` with the operator option, and `<Criteria>` with the search term to use in the search. See [Filter syntax for the query-alerts API command](#filter-syntax-for-the-query-alerts-api-command) below for details.

A successful response returns basic information about the alert notifications that match your search criteria, including the alert IDs of those notifications (look for the `"id":"value"` entry):

```json
{
  "type$": "ALERT_QUERY_RESPONSE",
  "alerts": [
    {
      "type$": "ALERT_SUMMARY",
      "tenantId": "123456",
      "type": "FED_ENDPOINT_EXFILTRATION",
      "name": "Departing employee endpoint exfiltration system rule",
      "description": "System rule for departing employee endpoint exfiltration.",
      "actor": "burt.morales@example.com",
      "target": "N/A",
      "severity": "HIGH",
      "ruleId": "123456789424242",
      "ruleSource": "Departing Employee",
      "id": "987654321424242",
      "createdAt": "2020-04-03T15:21:44.6139300Z",
      "state": "OPEN"
    }
  ],
  "totalCount": 1,
  "problems": []
}
```

#### Search for multiple alert notifications by alert IDs

After you've located the alert IDs for specific alerts, use the [/v1/alerts/query-details](/api#operation/Alerts_QueryAlertDetails) API command to search those IDs and view more details about those alert notifications.

```bash
curl -X POST "<RequestURL>/v1/alerts/query-details" \
-H "accept: text/plain" \
-H "Authorization: Bearer <AuthToken>" \
-H "Content-Type: application/json" \
-d '{ "alertIds": [ "<SampleAlertID1>", "<SampleAlertID2>" ]}'
```

In the preceding example, replace `<SampleAlertID1>` and `<SampleAlertID2>` with the IDs of the alert notifications. Enclose each ID in quotation marks and separate them with commas.

A successful response returns full details about the alert notifications, including a list of files involved in the activity.

```bash
{
  "type$": "ALERT_DETAILS_RESPONSE",
  "alerts": [
    {
      "type$": "ALERT_DETAILS",
      "tenantId": "123456",
      "type": "FED_ENDPOINT_EXFILTRATION",
      "name": "Departing employee endpoint exfiltration system rule",
      "description": "System rule for departing employee endpoint exfiltration.",
      "actor": "burt.morales@example.com",
      "target": "N/A",
      "severity": "HIGH",
      "ruleId": "123456789424242",
      "ruleSource": "Departing Employee",
      "id": "987654321424242",
      "createdAt": "2020-04-08T13:50:25.3644410Z",
      "state": "OPEN",
      "observations": [
        {
          "type$": "OBSERVATION",
          "id": "112233445566",
          "observedAt": "2020-04-08T13:40:00.0000000Z",
          "type": "FedEndpointExfiltration",
          "data": "{\"type$\":\"OBSERVED_ENDPOINT_ACTIVITY\",\"id\":\"665544332211\",\"sources\":[\"Endpoint\"],\"exposureTypes\":[\"ApplicationRead\",\"CloudStorage\"],\"firstActivityAt\":\"2020-04-08T13:40:00.0000000Z\",\"lastActivityAt\":\"2020-04-08T13:45:00.0000000Z\",\"fileCount\":2,\"totalFileSize\":311096,\"fileCategories\":[{\"type$\":\"OBSERVED_FILE_CATEGORY\",\"category\":\"Image\",\"fileCount\":2,\"totalFileSize\":311096,\"isSignificant\":false}],\"files\":[{\"type$\":\"OBSERVED_FILE\",\"eventId\":\"998877665544\",\"path\":\"C:/Users/burt.morales/\",\"name\":\"1586353274_family_photo.png\",\"category\":\"Image\"},{\"type$\":\"OBSERVED_FILE\",\"eventId\":\"334455667788\",\"path\":\"C:/Users/burt.morales/Dropbox/\",\"name\":\"1586353274_family_photo.png\",\"category\":\"Image\"}],\"syncToServices\":[\"Dropbox\"],\"sendingIpAddresses\":[\"192.0.2.0\"]}"
        }
      ]
    }
  ]
}
```


#### Add a note to an alert notification

To add a note to an alert notification, first locate its alert ID using one of the queries above. Then use the [/v1/alerts/add-note](/api#operation/Alerts_AddNoteToAlert) API command to add a note to that alert. Be aware that any note you add overwrites any existing note attached to the alert.

```bash
curl -X POST "<RequestURL>/v1/alerts/add-note" \
-H "accept: application/json" \
-H "Authorization: Bearer <AuthToken>" \
-H "Content-Type: application/json" \
-d '{ "tenantId": "<SampleTenant>", "alertId": "<SampleAlertID>", "note": "This is an example note." }'
```

In the preceding example, replace `<SampleAlertID>` with the alert ID.

#### Dismiss alert notifications

You can dismiss multiple alert notifications at once using the API. To dismiss alert notifications, first locate the alert IDs using one of the queries above. Then use the [/v1/alerts/update-state](/api#operation/Alerts_UpdateAlertState) API command with a `state` value of `RESOLVED` to dismiss those alerts.

```bash
curl -X POST "<RequestURL>/v1/alerts/update-state" \
-H "accept: application/json" \
-H "Authorization: Bearer <AuthToken>" \
-H "Content-Type: application/json" \
-d '{ "tenantId": "<SampleTenant>", "alertIds": [ "<SampleAlertID1>", "<SampleAlertID2>" ], "state": "RESOLVED", "note": "This is an example note."}'
```

In the preceding example, replace `<SampleAlertID1>` and `<SampleAlertID2>` with the IDs of the alert notifications. Enclose each ID in quotation marks and separate them with commas.

Be aware that any note you enter overwrites any existing note attached to the alert. If you want to dismiss the alert without adding a note (or want to preserve existing notes), delete the "note" term and sample text from the command.

#### Reopen dismissed alert notifications

You can reopen multiple dismissed alert notifications at once using the API. To reopen alert notifications, first locate the alert IDs using one of the queries above. Then use the [/v1/alerts/update-state](/api#operation/Alerts_UpdateAlertState) API command with the OPEN state value to reopen those alerts.

```bash
curl -X POST "<RequestURL>/v1/alerts/update-state" \
-H "accept: application/json" \
-H "Authorization: Bearer <AuthToken>" \
-H "Content-Type: application/json" \
-d '{ "tenantId": "<SampleTenant>", "alertIds": [ "<SampleAlertID1>", "<SampleAlertID2>" ], "state": "OPEN", "note": "This is an example note."}'
```

In the preceding example, replace `<SampleAlertID1>` and `<SampleAlertID2>` with the IDs of the alert notifications. Enclose each ID in quotation marks and separate them with commas.

Be aware that any note you enter overwrites any existing note attached to the alert. If you want to reopen the alert without adding a note (or want to preserve existing notes), delete the "note" term and sample text from the command.

#### Filter syntax for the query alerts API command

The [/v1/alerts/query-alerts](/api#operation/Alerts_QueryAlert) API uses these filter types, operators, and criteria values to search for alert notifications.

Filter Type | Operator | Criteria
-------------- | -------------- | --------------
CreatedAt | ON, ON_OR_AFTER, ON_OR_BEFORE | Date the alert was triggered, in yyyy-MM-dd format
Actor | IS, IS_NOT, CONTAINS, DOES_NOT_CONTAIN | The username or cloud alias (actor) of the person who caused the event, or portions thereof
Severity | IS, IS_NOT | HIGH, MEDIUM, or LOW
Name | IS, IS_NOT, CONTAINS, DOES_NOT_CONTAIN | The name of the rule, or portions thereof
Description | IS, IS_NOT, CONTAINS, DOES_NOT_CONTAIN | The description of the rule, or portions thereof
State | IS, IS_NOT | OPEN or DISMISSED
AlertID | IS | The ID of a specific alert notification



### Manage alert rule user lists

If a rule either applies only to specific users or applies to all users except specific users, you can manage the users in those inclusion or exclusion lists using the API. As with alert notifications, you'll need to identify the rule ID associated with the rule before you can manage the users to which it applies.

#### Locate alert rule IDs

Before you can manage the users associated with an alert rule, you need to view details about alert rules and identify the rule IDs for which you want to manage users. Use the [GET /v2/alert-rules](/api#operation/Rules_GetRules) API command to locate alert rule IDs.

**Note:** The API commands for alert notification searches described above also include the ID of the rule that generated the alert. Look for the "ruleID": `"<value>"` entry in the details returned by the query.

```bash
curl -X GET "<RequestURL>/v2/alert-rules" \
-H "accept: text/plain" \
-H "Authorization: Bearer <AuthToken>" \
-H "Content-Type: application/json" \
-d '{"PageSize": "20", "PageNumber": "0", "WatchlistId: "<watchlist_id>"}'
```

In the preceding example, replace `<watchlist_id>` with the ID of the watchlist.

A successful response returns basic information about the alert notifications that match your search criteria, including the rule IDs of those notifications (look for the `"id"` entry):

```json
    {
        "createdAt": "2021-04-27T02:11:07.4016710Z",
        "createdBy": "sean.cassidy@example.com",
        "modifiedAt": "2021-09-03T06:44:10.2802010Z",
        "modifiedBy": "jim.dandy@example.com",
        "isSystemRule": false,
        "id": "932281e9-4242-4ad0-b430-b4ea835c93b1",
        "name": "File Name Alert",
        "description": "",
        "isEnabled": true,
        "source": "Alerting",
        "notifications": {
            "isEnabled": false,
            "contacts": []
        },
```

#### View an alert rule's user list

Use the [GET /v2/alert-rules/{id}/users](/api#operation/Rules_GetUsers) API command to view a list of users that are either included in or excluded from a specific alert rule. The output from this command groups the user email addresses and cloud aliases in the rule's inclusion or exclusion list by the user ID associated with those details (which is generally the userUID value in Code42). You can then use this user ID to remove specific email addresses and cloud aliases from a rule's inclusion or exclusion list as needed.

```bash
curl -X GET "<RequestURL>/v2/alert-rules/<id>/users" \
-H "accept: text/plain" \
-H "Authorization: Bearer <AuthToken>" \
-H "Content-Type: application/json" 
```

In the preceding example, replace `<id>` with the ID of the alert rule for which you want to view users.

A successful response lists the email addresses and cloud aliases of the users in the alert rule's inclusion or exclusion list, grouped by the user ID value (identified by the "userIdFromAuthority" label) associated with that information. 

```json
{
    "id": "05bbf4e5-4242-47f9-b048-72c9a122de29",
    "users": [
        {
            "userIdFromAuthority": "Null UserIdFromAuthority.  These usernames must be edited in the web app.",
            "aliases": [
                "sean.cassidy@example.com",
                "jim.dandy@example"
            ]
        }
    ],
    "mode": 0
}

```

If a user ID was not provided when users were added to the alert rule (as is common when users are added using the Code42 command-line interface or manually with [Alerts in the Code42 console](https://support.code42.com/Administrator/Cloud/Code42_console_reference/Alerts_reference)), the results note that the "userIdFromAuthority" value is null. To work with an alert rule's inclusion or exclusion list if the user ID value is null, use the [Alerts screens in the Code42 console](https://support.code42.com/Administrator/Cloud/Code42_console_reference/Alerts_reference#Review_Alerts) to manually add and remove users. Alternately, you can use the [DELETE /v2/alert-rules/{id}/users](/api/#tag/Rules/operation/Rules_RemoveAllUsers) API command to remove all email addresses and aliases from a rule, and then re-add user information to that rule using the [POST /v2/alert-rules/{id}/users](/api/#tag/Rules/operation/Rules_AddUsers) using the users' userUID in Code42.

