## Search file events

Use the File Events API to search for file activity, also known as "Forensic Search". 


### Groups and filters

File Events API queries are organized by groups of filters. This structure facilitates complicated requests with multiple `AND` or `OR` conditions. For example, use case 1 in the [Sample use cases](#sample-use-cases) section searches for files matching any one of 11 different file extensions that also exist in any one of nine different locations. Search queries are limited to a total of 1,024 criteria per request.

For example, the JSON below uses two groups of filters:

* The first group uses a `filterClause` value of `OR`, which returns results if any of the four MD5 values are found (`db349b97c37d22f5ea1d1841e3c89eb4` or `84c82835a5d21bbcf75a61706d8ab549` or `f351e1fcca0c4ea05fc44d15a17f8b36` or `7bf2b57f2a205768755c07f238fb32cc`).

* The second group uses a `filterClause` value of `AND`, which returns results only if all criteria in the filter are met (in this example, `on or after 2022-06-01` **and** `on or before 2022-06-16`).

* Finally, to link these two groups together, the `groupClause` value of `AND` returns results only if both the first group and second group criteria are met.

```json
{
  "groups": [
    {
      "filters": [
        {
          "operator": "IS",
          "term": "file.hash.md5",
          "value": "db349b97c37d22f5ea1d1841e3c89eb4"
        },
        {
          "operator": "IS",
          "term": "file.hash.md5",
          "value": "84c82835a5d21bbcf75a61706d8ab549"
        },
        {
          "operator": "IS",
          "term": "file.hash.md5",
          "value": "f351e1fcca0c4ea05fc44d15a17f8b36"
        },
        {
          "operator": "IS",
          "term": "file.hash.md5",
          "value": "7bf2b57f2a205768755c07f238fb32cc"
        }
      ],
      "filterClause": "OR"
    },
    {
      "filters": [
        {
          "operator": "ON_OR_AFTER",
          "term": "@timestamp",
          "value": "2022-06-01T00:00:00.00Z"
        },
        {
          "operator": "ON_OR_BEFORE",
          "term": "@timestamp",
          "value": "2022-06-16T23:59:59.59Z"
        }
      ],
      "filterClause": "AND"
    }
  ],
  "groupClause": "AND",
  "pgNum": 1,
  "pgSize": 100,
  "srtDir": "asc",
  "srtKey": "@timestamp"
}
```

### Sample request

This simple example demonstrates a search for all files on all devices with the file extension `.docx` that exist anywhere except the file path `C:/Users`. For more complicated examples with multiple groups and additional filters, see the [sample use cases](#sample-use-cases) in the next section.

Use the following as a starting point for your own searches:

```bash
curl -X POST <RequestURL>/v2/file-events \
-H 'content-type: application/json' \
-H "authorization: Bearer <AuthToken>" \
-d '{
    "groups": [{
        "filters": [{
            "operator": "IS",
            "term": "file.name",
            "value": "*.docx"
        },
        {
            "operator": "IS_NOT",
            "term": "file.directory",
            "value": "C:/Users*"
        }
    ],
    "filterClause": "AND"
    }],
    "groupClause": "AND",
    "pgNum": 1,
    "pgSize": 100
}'
```

**Note:** To receive results in CSV format instead of JSON, use the [/v2/file-events/export](/api#operation/exportUsingPOST_1) resource instead of [/v2/file-events](/api#operation/searchEventsUsingPOST_1).

### API limits

* Request rate: To ensure optimal performance throughout your Code42 environment, Code42 limits API requests to 120 per minute. Requests that exceed this limit are blocked and do not return results.
* Result set:
  * `file-events` results are limited to 10,000 events per request. Requesting a page number that exceeds these limits returns an error (for example, a `file-events` query with `pgSize=10000` cannot display `pgNum=2`). To obtain more than 10,000 results, use the `pgToken` and `nextPgToken` request fields to submit multiple requests. (For `pgToken` implementation details, see the [/v2/file-events](/api#operation/searchEventsUsingPOST_1) API documentation.)
  * `file-events/export` queries are limited to 200,000 events.
  * `file-events/grouping` queries are limited to 1,000 groups

### Sample Use Cases

#### Use case 1: Search for application files in unexpected locations

The sample JSON below shows how to search for files with any of these extensions (.action, .app, .bat, .bin, .cmd, .com, .command, .cpl, .exe, .msc, .osx) that exist outside these locations:

* `C:\Program Files`
* `/Applications`
* `/Library`
* `/User/*/Applications`
* `/User/*/Library`
* `/usr/bin`
* `/usr/local/bin`
* `/sbin`
* `/bin`

##### Sample JSON search query for application files in specific locations

Modify this sample to fit your environment and then include it in a request (as shown in the [Sample request](#sample-request) section above).

```json
{
  "groups": [
    {
      "filters": [
        {
          "operator": "IS",
          "term": "file.name",
          "value": "*.action"
        },
        {
          "operator": "IS",
          "term": "file.name",
          "value": "*.app"
        },
        {
          "operator": "IS",
          "term": "file.name",
          "value": "*.bat"
        },
        {
          "operator": "IS",
          "term": "file.name",
          "value": "*.bin"
        },
        {
          "operator": "IS",
          "term": "file.name",
          "value": "*.cmd"
        },
        {
          "operator": "IS",
          "term": "file.name",
          "value": "*.com"
        },
        {
          "operator": "IS",
          "term": "file.name",
          "value": "*.command"
        },
        {
          "operator": "IS",
          "term": "file.name",
          "value": "*.cpl"
        },
        {
          "operator": "IS",
          "term": "file.name",
          "value": "*.exe"
        },
        {
          "operator": "IS",
          "term": "file.name",
          "value": "*.msc"
        },
        {
          "operator": "IS",
          "term": "file.name",
          "value": "*.osx"
        }
      ],
      "filterClause": "OR"
    },
    {
      "filters": [
        {
          "operator": "IS_NOT",
          "term": "file.directory",
          "value": "C:\\Program Files*"
        },
        {
          "operator": "IS_NOT",
          "term": "file.directory",
          "value": "/Applications*"
        },
        {
          "operator": "IS_NOT",
          "term": "file.directory",
          "value": "/Library*"
        },
        {
          "operator": "IS_NOT",
          "term": "file.directory",
          "value": "/User/*/Applications*"
        },
        {
          "operator": "IS_NOT",
          "term": "file.directory",
          "value": "/User/*/Library*"
        },
        {
          "operator": "IS_NOT",
          "term": "file.directory",
          "value": "/usr/bin*"
        },
        {
          "operator": "IS_NOT",
          "term": "file.directory",
          "value": "/usr/local/bin*"
        },
        {
          "operator": "IS_NOT",
          "term": "file.directory",
          "value": "/sbin*"
        },
        {
          "operator": "IS_NOT",
          "term": "file.directory",
          "value": "/bin*"
        }
      ],
      "filterClause": "AND"
    }
  ],
  "groupClause": "AND",
  "pgNum": 1,
  "pgSize": 100,
  "srtDir": "asc",
  "srtKey": "@timestamp"
}
```

##### Sample results of application files in specific locations

```json
{
  "totalCount":1,
  "fileEvents":[
        {
            "@timestamp": "2022-04-19T16:42:37.943Z",
            "event": {
                "id": "0_1a88974e-4675-41cc-8792-7256d16f7d4a_963040578383726480_1056359497080919794_724",
                "inserted": "2022-04-19T16:49:25.778583Z",
                "action": "file-modified",
                "observer": "Endpoint",
                "shareType": []
            },
            "user": {
                "email": "jim.harper@example.com",
                "id": "851380922911151622",
                "deviceUid": "963040578383726482"
            },
            "file": {
                "name": "Updater.exe",
                "directory": "C:/myapps/",
                "category": "Executable",
                "mimeTypeByBytes": "application/x-msdownload",
                "categoryByBytes": "Executable",
                "mimeTypeByExtension": "application/x-dosexec",
                "categoryByExtension": "Executable",
                "sizeInBytes": 4200864,
                "owner": "qa",
                "created": "2019-05-21T18:43:25.690Z",
                "modified": "2022-04-19T16:42:05.570Z",
                "hash": {
                    "md5": "792e95b64b9cf45ac8bc10d4d0f077c4",
                    "sha256": "60e64dd2c6d2ac6fe9b498fadac81bc34a725de5d893e7df8b2728d8dc5b194d",
                    "md5Error": null,
                    "sha256Error": null
                },
                "id": null,
                "url": null,
                "directoryId": [],
                "cloudDriveId": null,
                "classifications": []
            },
            "report": {
                "id": null,
                "name": null,
                "description": null,
                "headers": [],
                "count": null,
                "type": null
            },
            "source": {
                "category": null,
                "name": null,
                "domain": "203.0.113.0",
                "ip": "233.252.0.0",
                "privateIp": [
                    "203.0.113.0",
                    "0:0:0:0:0:0:0:1",
                    "fe80:0:0:0:3549:20c6:c7c8:42d5%eth3",
                    "192.0.2.0"
                ],
                "operatingSystem": "Windows 10",
                "email": {
                    "sender": null,
                    "from": null
                },
                "removableMedia": {
                    "vendor": null,
                    "name": null,
                    "serialNumber": null,
                    "capacity": null,
                    "busType": null,
                    "mediaName": null,
                    "volumeName": [],
                    "partitionId": []
                },
                "tabs": [],
                "domains": []
            },
            "destination": {
                "category": null,
                "name": null,
                "user": {
                    "email": []
                },
                "ip": null,
                "privateIp": [],
                "operatingSystem": null,
                "printJobName": null,
                "printerName": null,
                "printedFilesBackupPath": null,
                "removableMedia": {
                    "vendor": null,
                    "name": null,
                    "serialNumber": null,
                    "capacity": null,
                    "busType": null,
                    "mediaName": null,
                    "volumeName": [],
                    "partitionId": []
                },
                "email": {
                    "recipients": null,
                    "subject": null
                },
                "tabs": [],
                "accountName": null,
                "accountType": null,
                "domains": []
            },
            "process": {
                "executable": null,
                "owner": null
            },
            "risk": {
                "score": 0,
                "severity": "NO_RISK_INDICATED",
                "indicators": [],
                "trusted": false,
                "trustReason": null
            }
        }
    ],
    "nextPgToken": null,
    "problems": null
}


```

#### Use case 2: Search for files on a device within a specific date range based on MD5 values

The sample JSON below shows how to search for files files matching any of four MD5 values that existed on devices between June 1 and 16, 2022.

**Note:** To search for SHA256 hash values instead of MD5, replace `file.hash.md5` with `file.hash.sha256` in the sample JSON below.

##### Sample JSON search query for MD5 values between two dates

Modify this sample to fit your environment and then include it in a request (as shown in the [Sample request](#sample-request) section above).

```json
{
  "groups": [
    {
      "filters": [
        {
          "operator": "IS",
          "term": "file.hash.md5",
          "value": "2a67b45426cfd30acd4997353ec02a94"
        },
        {
          "operator": "IS",
          "term": "file.hash.md5",
          "value": "84c82835a5d21bbcf75a61706d8ab549"
        },
        {
          "operator": "IS",
          "term": "file.hash.md5",
          "value": "f351e1fcca0c4ea05fc44d15a17f8b36"
        },
        {
          "operator": "IS",
          "term": "file.hash.md5",
          "value": "7bf2b57f2a205768755c07f238fb32cc"
        }
      ],
      "filterClause": "OR"
    },
    {
      "filters": [
        {
          "operator": "ON_OR_AFTER",
          "term": "@timestamp",
          "value": "2022-06-01T00:00:00.00Z"
        },
        {
          "operator": "ON_OR_BEFORE",
          "term": "@timestamp",
          "value": "2022-06-16T23:59:59.59Z"
        }
      ],
      "filterClause": "AND"
    }
  ],
  "groupClause": "AND",
  "pgNum": 1,
  "pgSize": 100,
  "srtDir": "asc",
  "srtKey": "@timestamp"
}
```

##### Sample results of file events matching the MD5 values and date range

```json
{
  "totalCount": 1,
  "fileEvents": [
        {
            "@timestamp": "2022-06-15T22:33:14.078Z",
            "event": {
                "id": "0_1a88974e-4675-41cc-8792-7256d16f7d4a_963040578383726480_1064656813338231764_13",
                "inserted": "2022-06-15T22:35:28.477386Z",
                "action": "file-created",
                "observer": "Endpoint",
                "shareType": []
            },
            "user": {
                "email": "jim.harper@example.com",
                "id": "851380922911151620",
                "deviceUid": "963040578383726480"
            },
            "file": {
                "name": "2022_customer_list.docx",
                "directory": "C:/Users/qa/Documents/",
                "category": "Document",
                "mimeTypeByBytes": "text/plain",
                "categoryByBytes": "Document",
                "mimeTypeByExtension": "text/plain",
                "categoryByExtension": "Document",
                "sizeInBytes": 33,
                "owner": "qa",
                "created": "2022-06-15T22:33:13.255Z",
                "modified": "2022-06-15T22:33:13.294Z",
                "hash": {
                    "md5": "2a67b45426cfd30acd4997353ec02a94",
                    "sha256": "899359b93c1a86e0bc0cd412ff01f1241f947a4768a1214e3fec1e1082f6d42b",
                    "md5Error": null,
                    "sha256Error": null
                },
                "id": null,
                "url": null,
                "directoryId": [],
                "cloudDriveId": null,
                "classifications": []
            },
            "report": {
                "id": null,
                "name": null,
                "description": null,
                "headers": [],
                "count": null,
                "type": null
            },
            "source": {
                "category": null,
                "name": null,
                "domain": "203.0.113.0",
                "ip": "233.252.0.0",
                "privateIp": [
                    "203.0.113.0",
                    "0:0:0:0:0:0:0:1",
                    "fe80:0:0:0:3549:20c6:c7c8:42d5%eth3",
                    "192.0.2.0"
                ],
                "operatingSystem": "Windows 10",
                "email": {
                    "sender": null,
                    "from": null
                },
                "removableMedia": {
                    "vendor": null,
                    "name": null,
                    "serialNumber": null,
                    "capacity": null,
                    "busType": null,
                    "mediaName": null,
                    "volumeName": [],
                    "partitionId": []
                },
                "tabs": [],
                "domains": []
            },
            "destination": {
                "category": null,
                "name": null,
                "user": {
                    "email": []
                },
                "ip": null,
                "privateIp": [],
                "operatingSystem": null,
                "printJobName": null,
                "printerName": null,
                "printedFilesBackupPath": null,
                "removableMedia": {
                    "vendor": null,
                    "name": null,
                    "serialNumber": null,
                    "capacity": null,
                    "busType": null,
                    "mediaName": null,
                    "volumeName": [],
                    "partitionId": []
                },
                "email": {
                    "recipients": null,
                    "subject": null
                },
                "tabs": [],
                "accountName": null,
                "accountType": null,
                "domains": []
            },
            "process": {
                "executable": null,
                "owner": null
            },
            "risk": {
                "score": 0,
                "severity": "NO_RISK_INDICATED",
                "indicators": [],
                "trusted": false,
                "trustReason": null
            }
        },
    ],
    "nextPgToken": null,
    "problems": null
```

#### Use case 3: See all cloud sync destinations for a user

The sample JSON below shows how to use the [/v2/file-events/grouping](/api#operation/groupingUsingPOST_1) resource to find an approximate count of **Synced to cloud service** file events for a specific user for each cloud service. This sample groups by the `destination.name` value, but you can choose any `groupingTerm` listed in the [/v2/file-events/grouping](/api#operation/groupingUsingPOST_1) API documentation in your requests.

##### Sample JSON search query for cloud service file event counts

Modify this sample to fit your environment and then include it in a request (as shown in the [Sample request](#sample-request) section above). For grouping queries, you must use the [/v2/file-events/grouping](/api#operation/groupingUsingPOST_1) resource.

```json
{
  "groupingTerm": "destination.name",
  "groups": [
    {
      "filters": [
        {
          "operator": "IS",
          "term": "user.email",
          "value": "jim.harper@example.com"
        }
      ]
    }
  ]
}
```

##### Sample results of cloud service file event counts

```json
{
    "groups": [
        {
            "value": "google drive",
            "docCount": 52974
        },
        {
            "value": "dropbox",
            "docCount": 20
        },
        {
            "value": "gmail",
            "docCount": 14
        },
        {
            "value": "uncategorized",
            "docCount": 3
        }
    ],
    "problems": null
}
```

**Missing or unknown values**

Some file events may not capture all metadata. Reasons for omitted metadata can include:

* The file did not exist on disk long enough for Code42 to capture all the metadata.
* Several values, including `user.email` and `user.id`, are captured and reported from the Code42 cloud instead of directly from the user device. If those values haven't been reported yet, they may be blank or may display as `UNKNOWN` or `NAME_NOT_AVAILABLE`.
