## Use case: Track file activity of a high risk employee

This use case shows how to run different APIs in sequence to manage a high risk employee from the time they are identified to when you no longer need to monitor their file activity:

1. Add the user to a watchlist.
2. Add the user to an alert rule.
3. Search for alerts the user triggered.
4. Remove the user from the watchlist when tracking is no longer desired.


### Before you begin

#### Plan your work

Before you start writing scripts using the Code42 APIs, consider the following questions to help you plan your work:

**Why do you want to automate adding users to watchlists?**

Adding users to watchlists automatically provides economies of scale. If you monitor insider risk at a small company, you could use the [watchlists in the Code42 console](https://support.code42.com/Administrator/Cloud/Monitoring_and_managing/Manage_watchlists) to track file activity for high risk employees. But for larger companies with many more employees to track, automating the process with the Code42 API provides a much faster and efficient method. As an added benefit, you can [integrate the Code42 APIs](https://support.code42.com/Administrator/Cloud/Monitoring_and_managing/Code42_integrations_resources) with other systems such as your company's security tools. Planning and implementing Code42 APIs can take some time. Before you begin using Code42 APIs to manage high risk employees, consider the effort involved to set them up against the time savings provided when they run.

**What are the kinds of alerts you want to receive?**

The primary reason to add users to watchlists is to receive alerts when those users perform actions that are considered high risk. Before you start adding users, determine the kinds of actions that you want to receive alerts about and then [create alerts](https://support.code42.com/Administrator/Cloud/Monitoring_and_managing/How_to_create_a_security_alert) that will be triggered by those actions. Creating the right kinds of alerts provides the best monitoring possible of your the file activity of high risk employees.

**What other systems with data about risk factors should you consider?**

When determining risk factors to assign to employees, consider where else to look for supporting evidence, such as HR systems, security scanning tools, access management applications, Internet access monitoring tools, and so on. These can all provide additional information that you can place in the notes for the high risk employees, which will help guide any investigations that might be opened on these users.

#### Gather your inputs

Before attempting to write scripts using the Code42 API examples in this article, gather the following inputs:

* **Authentication token**

[Authentication tokens](#authentication) are required to run the APIs. 

* **Tenant ID**

Your company's entity in the Code42 cloud is known as a "tenant". To obtain your tenant ID, use your Code42 administrator credentials to submit a request to the [customer API](/api/#tag/Customer).

* **Code42 usernames for the people you want to add to the watchlists**

You need the Code42 usernames of employees to add them to watchlists. The Code42 username is assigned when the user is [added to Code42](https://support.code42.com/Administrator/Cloud/Configuring/Add_users_from_the_Code42_console#Add_users_manually). You can obtain usernames via [CSV export](https://support.code42.com/Administrator/Cloud/Code42_console_reference/Users_reference#CSV_export), [user reports](https://support.code42.com/Administrator/Cloud/Code42_console_reference/User_Backup_report_reference#User_Backup_report), or the [Users API](#tag/User).


### Step 1: Add the user to a watchlist

To add the user to a watchlist, use the [/v1/watchlists/\<watchlist_id\>/included-users/add](/api#operation/AddIncludedUsers) API command.

```bash
curl -X POST <requestURL>/v1/watchlists/<watchlist_id>/included-users/add \
-H 'content-type: application/json' \
-H "authorization: Bearer <AuthToken>" \
-d '{"userIds": ["<userUIDs>"]}'
```

In the preceding example:

* Replace `<watchlist_id>` with the watchlist ID obtained from the [/v1/watchlists](/api#operation/ListWatchlists) API command.
* Replace `<userUIDs>` with the user's userUID in Code42. 



### Step 2: Add the user to an alert rule

Do the following to add the user to alerts using the APIs. 

#### Add the user to default watchlist rules

When the user is added to a watchlist they are automatically added to the the watchlist's default alert rules. There is no need to use the API to add the user to, or remove a user from, the default alert rules.

To receive alerts from the watchlist, enable the watchlist's alert rules using the [POST /v2/alert-rules/enable](/api/#tag/Rules/operation/Rules_Enable2) API command.

#### Add the user to other alert rules

You can use the API to add the user to other existing [alert rules](https://support.code42.com/Administrator/Cloud/Code42_console_reference/Alerts_reference#Manage_Rules) that monitor user file activity.


### Step 3: Search for alerts the user triggered

To find alerts triggered by the user, search for alerts with the Actor filter using the [/v1/alerts/query-alerts](/api#operation/Alerts_QueryAlert) API command as shown in the following example:

```bash
curl -X POST <RequestURL>/v1/alerts/query-alerts \
-H "accept: text/plain" \
-H "Authorization: Bearer <AuthToken>" \
-H "Content-Type: application/json" \
-d '{
    "tenantId": "<SampleTenant>",
    "groups": [
        {
            "filters": [
                {
                    "term": "Actor",
                    "operator": "Is",
                    "value": "<ActorUsername>"
                }
            ],
            "filterClause": "AND"
        }
    ],
    "groupClause": "OR",
    "pgSize": "20",
    "pgNum": "0",
    "srtKey": "CreatedAt",
    "srtDirection": "DESC"
}'
```

In the preceding example, replace `<ActorUsername>` with the Code42 username of the user.

A successful response returns basic information about the alert notifications that match your search criteria, including the alert IDs of those notifications (look for the `"id":"value"` entry):

```json
{
  "type$": "ALERT_SUMMARY",
  "tenantId": "123456",
  "type": "FED_ENDPOINT_EXFILTRATION",
  "name": "Exposure on an endpoint from High Risk Employees system rule",
  "description": "System rule for exposure on an endpoint from High Risk Employees.",
  "actor": "burt.morales@example.com",
  "target": "N/A",
  "severity": "HIGH",
  "ruleId": "123456789424242",
  "ruleSource": "High Risk Employee",
  "id": "987654321424242",
  "createdAt": "2020-04-03T15:21:44.6139300Z",
  "state": "OPEN"
}
```

#### Filter alerts

You can further filter alerts by adding more filter types. For example, you could use the `Severity` filter to find only those alerts that were high severity, or the `RuleName` filter to find only alerts from a particular rule.

#### Search the user's file activity

In addition to using alerts to identify file activity, you can use the [File Events API](/api#tag/File-Events) to search for the user's file activity.



### Step 4: Remove the user from the watchlist when tracking is no longer desired

You can remove the user from the watchlist using the [/v1/watchlists/\<watchlist_id\>/included-users/delete](/api#operation/DeleteIncludedUsers) API.  

```bash
curl -X POST <requestURL>/v1/watchlists/<watchlist_id>/included-users/delete \
-H 'content-type: application/json' \
-H "authorization: Bearer <AuthToken>" \
-d '{"userIds": ["<userUIDs>"],"watchlistId": "<WatchlistID>"}'
```

In the preceding example:

* Replace `<userUIDs>` with the user's user UID in Code42.
* Replace `<WatchlistID>` with the watchlist ID.


To verify that the user is removed, obtain a listing of all users in the detection list by running the [/v1/watchlists/\<watchlist_id\>/included-users](/api#operation/ListIncludedUsers) API command.



